name: 'Publish to conda'
description: 'Publish conda package'
author: 'JoGruen'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  CondaDir:
    description: 'directory containing your meta.yml file'
    default: 'conda'
  Channels:
    description: 'Channels to use'
    default: 'conda-forge'
  Platforms: 
    description: 'input plaftorms'
    default: 'osx-64 linux-32 linux-64 win-32 win-64'
  CondaToken:
    description: 'conda Token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
